services:
  e621-bot-rewrite:
    image: ghcr.io/bakatrouble/e621-bot-rewrite:latest
    container_name: e621-bot-rewrite
    volumes:
      - /srv/apps/e621-bot-rewrite/config.yaml:/app/config.yaml
      - /srv/apps/e621-bot-rewrite/cache:/app/cache.yaml
    # environment:
    #   OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
    #   OTEL_ENVIRONMENT: production
