[supervisord]
nodaemon = true

[program:telegram-bot]
command = uv run python main.py telegram-bot
directory = /app
autostart = true
autorestart = true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:worker]
command = uv run python main.py worker
directory = /app
autostart = true
autorestart = true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:api-server]
command = uv run python main.py api-server
directory = /app
autostart = true
autorestart = true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

